[[headers]]
  for ="*"
    [headers.values]
      Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=()"
      Referrer-Policy = "same-origin"
      Strict-Transport-Security = "max-age=2592000; includeSubdomains; preload"

      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      X-Permitted-Cross-Domain-Policies = "none"

[[redirects]]
  from = "https://juek3y.netlify.app/*"
  to = "https://juek3y.com"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/page-not-found"
  status = 404  

[[redirects]]
  from = "/*"
  to = "/en/coming-soon"
  status = 302

[[redirects]]
  from = "/impressum"
  to = "/impressum.html"
  status = 200

[[redirects]]
  from = "/impressum.html"
  to = "/impressum.html"
  status = 200

[[redirects]]
  from = "/1000days/*"
  to = "/1000days/:splat"
  status = 200
