[[headers]]
  for ="*"
    [headers.values]
      Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=()"
      Referrer-Policy = "same-origin"
      Strict-Transport-Security = "max-age=2592000; includeSubdomains; preload"


[[redirects]]
  from = "https://juek3y.netlify.app/*"
  to = "https://juek3y.com"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/page-not-found"
  status = 404  


[[redirects]]
  from = "/*"
  to = "/en/coming-soon"
  status = 302
